"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type SaleType = "General" | "Familia";
type Product = { id:number; name:string; category:string; quantity:number; cost:number; publicPrice:number; familyPrice:number; soldQuantity:number; salesRevenue:number; status?:string; saleType?:SaleType; soldPrice?:number };
type Reservation = { id:number; productId:number; quantity:number; saleType:SaleType; createdAt:string };
type Delivery = { id:number; client:string; phone:string; date:string; time:string; address:string; details:string; price:number };
type Tab = "inicio" | "productos" | "agenda";

const now = new Date();
const isoDate = (date:Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const datePlus = (days:number) => { const d=new Date(); d.setDate(d.getDate()+days); return isoDate(d); };
const demoProducts:Product[] = [
  {id:1,name:"Vela Lavanda",category:"Velas",quantity:12,cost:4.25,publicPrice:8.50,familyPrice:7,soldQuantity:0,salesRevenue:0},
  {id:2,name:"Jabón de avena",category:"Cuidado",quantity:6,cost:1.75,publicPrice:4,familyPrice:3.25,soldQuantity:0,salesRevenue:0},
  {id:3,name:"Caja regalo",category:"Regalos",quantity:5,cost:9,publicPrice:18,familyPrice:15,soldQuantity:2,salesRevenue:36},
  {id:4,name:"Aceite de rosas",category:"Cuidado",quantity:4,cost:5.50,publicPrice:11.50,familyPrice:9.50,soldQuantity:0,salesRevenue:0},
];
const demoDeliveries:Delivery[] = [
  {id:1,client:"Ana Martínez",phone:"7845-2210",date:datePlus(0),time:"10:30",address:"Colonia Escalón, San Salvador",details:"2 velas de lavanda",price:17},
  {id:2,client:"Carlos Méndez",phone:"7012-8890",date:datePlus(2),time:"15:00",address:"Santa Tecla",details:"1 caja de regalo",price:18},
];

const money=(n:number)=>new Intl.NumberFormat("es-SV",{style:"currency",currency:"USD"}).format(n||0);
const fullDate=(s:string)=>new Intl.DateTimeFormat("es-SV",{weekday:"long",day:"numeric",month:"long"}).format(new Date(`${s}T12:00:00`));

export default function Home(){
  const [tab,setTab]=useState<Tab>("inicio");
  const [products,setProducts]=useState<Product[]>(demoProducts);
  const [reservations,setReservations]=useState<Reservation[]>([{id:101,productId:2,quantity:2,saleType:"Familia",createdAt:datePlus(0)}]);
  const [categories,setCategories]=useState<string[]>(["Velas","Cuidado","Regalos"]);
  const [deliveries,setDeliveries]=useState<Delivery[]>(demoDeliveries);
  const [query,setQuery]=useState("");
  const [productView,setProductView]=useState<"inventory"|"reserved">("inventory");
  const [modal,setModal]=useState<"product"|"delivery"|"movement"|null>(null);
  const [movementType,setMovementType]=useState<"sale"|"reserve">("sale");
  const [editing,setEditing]=useState<Product|null>(null);
  const [selected,setSelected]=useState<Product|null>(null);
  const [toast,setToast]=useState("");
  const [selectedDate,setSelectedDate]=useState(isoDate(now));
  const [month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1));

  useEffect(()=>{const raw=localStorage.getItem("tallercito-v2");if(raw){try{const d=JSON.parse(raw);const migratedReservations:Reservation[]=d.reservations??[];const loaded:Product[]=d.products.map((p:Product)=>{const quantity=p.quantity??1;const wasSold=p.status==="Vendido";if(p.status==="Reservado"&&!migratedReservations.some(r=>r.productId===p.id))migratedReservations.push({id:Date.now()+p.id,productId:p.id,quantity,saleType:"General",createdAt:isoDate(now)});return{...p,quantity,soldQuantity:p.soldQuantity??(wasSold?quantity:0),salesRevenue:p.salesRevenue??(wasSold?(p.soldPrice??p.publicPrice)*quantity:0)}});setProducts(loaded);setReservations(migratedReservations);setDeliveries(d.deliveries);setCategories(d.categories??Array.from(new Set(loaded.map(p=>p.category))))}catch{}}},[]);
  useEffect(()=>{localStorage.setItem("tallercito-v2",JSON.stringify({products,deliveries,categories,reservations}))},[products,deliveries,categories,reservations]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2800);return()=>clearTimeout(t)},[toast]);

  const invested=useMemo(()=>products.reduce((s,p)=>s+p.cost*p.soldQuantity,0),[products]);
  const revenue=useMemo(()=>products.reduce((s,p)=>s+p.salesRevenue,0),[products]);
  const profit=revenue-invested;
  const upcoming=deliveries.filter(d=>d.date>=isoDate(now)).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
  const filtered=products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
  const dayDeliveries=deliveries.filter(d=>d.date===selectedDate).sort((a,b)=>a.time.localeCompare(b.time));

  function saveProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const newCategory=String(f.get("newCategory")||"").trim();const category=newCategory||String(f.get("category"));const values={name:String(f.get("name")),category,quantity:Number(f.get("quantity")),cost:Number(f.get("cost")),publicPrice:Number(f.get("publicPrice")),familyPrice:Number(f.get("familyPrice"))};if(newCategory&&!categories.includes(newCategory))setCategories(x=>[...x,newCategory].sort());if(editing){setProducts(x=>x.map(p=>p.id===editing.id?{...p,...values}:p));setToast("Producto actualizado")}else{setProducts(x=>[{id:Date.now(),soldQuantity:0,salesRevenue:0,...values},...x]);setToast("Producto agregado")};setEditing(null);setModal(null)}
  function saveDelivery(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setDeliveries(x=>[...x,{id:Date.now(),client:String(f.get("client")),phone:String(f.get("phone")),date:String(f.get("date")),time:String(f.get("time")),address:String(f.get("address")),details:String(f.get("details")),price:Number(f.get("price"))}]);setSelectedDate(String(f.get("date")));setModal(null);setToast("Entrega agregada al calendario")}
  const reservedFor=(id:number)=>reservations.filter(r=>r.productId===id).reduce((s,r)=>s+r.quantity,0);
  const availableFor=(p:Product)=>Math.max(0,p.quantity-p.soldQuantity-reservedFor(p.id));
  function openMovement(p:Product,type:"sale"|"reserve"){setSelected(p);setMovementType(type);setModal("movement")}
  function confirmMovement(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget),quantity=Number(f.get("quantity")),saleType=String(f.get("saleType")) as SaleType;if(quantity<1||quantity>availableFor(selected))return;const price=saleType==="Familia"?selected.familyPrice:selected.publicPrice;if(movementType==="reserve"){setReservations(x=>[...x,{id:Date.now(),productId:selected.id,quantity,saleType,createdAt:isoDate(now)}]);setToast(`${quantity} unidad${quantity===1?"":"es"} reservada${quantity===1?"":"s"}`)}else{setProducts(x=>x.map(p=>p.id===selected.id?{...p,soldQuantity:p.soldQuantity+quantity,salesRevenue:p.salesRevenue+price*quantity}:p));setToast(`Venta guardada. Ganancia: ${money((price-selected.cost)*quantity)}`)}setModal(null);setSelected(null)}
  function completeReservation(r:Reservation){const p=products.find(x=>x.id===r.productId);if(!p)return;const price=r.saleType==="Familia"?p.familyPrice:p.publicPrice;setProducts(x=>x.map(item=>item.id===p.id?{...item,soldQuantity:item.soldQuantity+r.quantity,salesRevenue:item.salesRevenue+price*r.quantity}:item));setReservations(x=>x.filter(item=>item.id!==r.id));setToast("Reserva marcada como vendida e inventario actualizado")}
  function releaseReservation(r:Reservation){setReservations(x=>x.filter(item=>item.id!==r.id));setToast("Reserva liberada; las unidades están disponibles")}
  function openEdit(p:Product){setEditing(p);setModal("product")}
  function openDelivery(date=selectedDate){setSelectedDate(date);setModal("delivery")}

  return <main className="app-shell">
    <header className="topbar"><div className="brand-mark">Y</div><div><span className="eyebrow">MI EMPRENDIMIENTO</span><h1>Variedades YesKar</h1></div></header>
    <div className="content">
      {tab==="inicio"&&<>
        <section className="welcome"><div className="welcome-copy"><p>{fullDate(isoDate(now))}</p><h2>¡Hola, Yesi!</h2><span>Aquí tienes lo más importante de hoy.</span></div><img className="mascot" src="/images/yeskar-elephant-v2.png" alt="Elefantito con mochila, mascota de Variedades YesKar"/></section>
        <section className="section-title"><h2>Resumen de ventas</h2><p>Calculado con los productos marcados como vendidos.</p></section>
        <div className="money-grid"><article><span>Dinero recogido</span><strong>{money(revenue)}</strong></article><article><span>Dinero gastado</span><strong>{money(invested)}</strong></article><article className="profit"><span>Ganancia total</span><strong>{money(profit)}</strong></article></div>
        <div className="home-actions"><button onClick={()=>{setEditing(null);setModal("product")}}><b>＋</b><span><strong>Agregar producto</strong><small>Registrar un artículo nuevo</small></span></button><button onClick={()=>openDelivery(isoDate(now))}><b>＋</b><span><strong>Agendar entrega</strong><small>Crear una cita en el calendario</small></span></button></div>
        <section className="section-title row"><div><h2>Próximas entregas</h2><p>{upcoming.length} entrega{upcoming.length===1?"":"s"} pendiente{upcoming.length===1?"":"s"}</p></div><button onClick={()=>setTab("agenda")}>Ver calendario</button></section>
        <div className="simple-list">{upcoming.slice(0,3).map(d=><DeliveryCard key={d.id} delivery={d}/>)}</div>
      </>}
      {tab==="productos"&&<>
        <section className="page-title"><div><h2>Productos</h2><p>{products.reduce((sum,p)=>sum+availableFor(p),0)} unidades disponibles.</p></div><button className="action" onClick={()=>{setEditing(null);setModal("product")}}>＋ Agregar</button></section>
        <div className="product-tabs"><button className={productView==="inventory"?"active":""} onClick={()=>setProductView("inventory")}>Inventario</button><button className={productView==="reserved"?"active":""} onClick={()=>setProductView("reserved")}>Reservados <b>{reservations.reduce((s,r)=>s+r.quantity,0)}</b></button></div>
        {productView==="inventory"?<><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre…" aria-label="Buscar productos"/></label><div className="category-line">{categories.map(c=><span key={c}>{c}</span>)}</div><div className="product-list">{filtered.map(p=><ProductCard key={p.id} product={p} available={availableFor(p)} reserved={reservedFor(p.id)} onEdit={openEdit} onMovement={openMovement}/>)}</div>{!filtered.length&&<div className="empty"><b>No hay productos aquí</b><span>Prueba otra búsqueda o agrega uno nuevo.</span></div>}</>:<ReservedList reservations={reservations} products={products} onComplete={completeReservation} onRelease={releaseReservation}/>} 
      </>}
      {tab==="agenda"&&<>
        <section className="page-title"><div><h2>Calendario</h2><p>Selecciona un día para ver sus entregas.</p></div><button className="action" onClick={()=>openDelivery()}>＋ Agregar</button></section>
        <Calendar month={month} selected={selectedDate} deliveries={deliveries} onMonth={setMonth} onSelect={setSelectedDate}/>
        <section className="selected-day"><div><span>ENTREGAS DEL DÍA</span><h2>{fullDate(selectedDate)}</h2></div><button onClick={()=>openDelivery()}>＋ Nueva entrega</button></section>
        <div className="simple-list">{dayDeliveries.map(d=><DeliveryCard key={d.id} delivery={d}/>)}</div>{!dayDeliveries.length&&<div className="empty calendar-empty"><b>No hay entregas este día</b><span>Puedes agregar una con el botón de arriba.</span></div>}
      </>}
    </div>
    <nav className="bottom-nav" aria-label="Navegación principal"><button className={tab==="inicio"?"active":""} onClick={()=>setTab("inicio")}><b>⌂</b><span>Inicio</span></button><button className={tab==="productos"?"active":""} onClick={()=>setTab("productos")}><b>▦</b><span>Productos</span></button><button className={tab==="agenda"?"active":""} onClick={()=>setTab("agenda")}><b>□</b><span>Calendario</span></button></nav>
    {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setModal(null);setEditing(null)}}}><section className="modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>{setModal(null);setEditing(null)}} aria-label="Cerrar">×</button>{modal==="product"&&<ProductForm product={editing} categories={categories} onSubmit={saveProduct}/>} {modal==="delivery"&&<DeliveryForm date={selectedDate} onSubmit={saveDelivery}/>} {modal==="movement"&&selected&&<MovementForm product={selected} available={availableFor(selected)} type={movementType} onSubmit={confirmMovement}/>}</section></div>}{toast&&<div className="toast">✓ {toast}</div>}
  </main>
}

function ProductCard({product:p,available,reserved,onEdit,onMovement}:{product:Product;available:number;reserved:number;onEdit:(p:Product)=>void;onMovement:(p:Product,t:"sale"|"reserve")=>void}){return <article className="product-card"><button className="product-main" onClick={()=>onEdit(p)}><div className="product-image">{p.name.charAt(0)}</div><div><span className={`state ${available?"disponible":"vendido"}`}>{available?"Disponible":"Agotado"}</span><h3>{p.name}</h3><p>{p.category}{reserved?` · ${reserved} reservadas`:""}</p></div><span className="quantity"><b>{available}</b><small>disponibles</small></span></button><div className="prices"><span><small>Compra por unidad</small><b>{money(p.cost)}</b></span><span><small>Venta general</small><b>{money(p.publicPrice)}</b></span><span className="gain"><small>Venta familia</small><b>{money(p.familyPrice)}</b></span></div><button className="edit-product" onClick={()=>onEdit(p)}>Editar producto y cantidad</button><div className="status-actions"><button className="reserve" disabled={!available} onClick={()=>onMovement(p,"reserve")}>Reserva</button><button className="sell" disabled={!available} onClick={()=>onMovement(p,"sale")}>Venta</button></div>{p.soldQuantity>0&&<div className="sold-note">{p.soldQuantity} unidad{p.soldQuantity===1?"":"es"} vendida{p.soldQuantity===1?"":"s"} hasta ahora</div>}</article>}

function ReservedList({reservations,products,onComplete,onRelease}:{reservations:Reservation[];products:Product[];onComplete:(r:Reservation)=>void;onRelease:(r:Reservation)=>void}){if(!reservations.length)return <div className="empty reserved-empty"><b>No hay productos reservados</b><span>Las nuevas reservas aparecerán aquí.</span></div>;return <div className="reserved-list">{reservations.map(r=>{const p=products.find(x=>x.id===r.productId);if(!p)return null;const price=r.saleType==="Familia"?p.familyPrice:p.publicPrice;return <article className="reserved-card" key={r.id}><header><div className="product-image">{p.name.charAt(0)}</div><div><span>RESERVADO · {r.saleType}</span><h3>{p.name}</h3><p>{r.quantity} unidad{r.quantity===1?"":"es"} · Total {money(price*r.quantity)}</p></div></header><div className="reserved-actions"><button onClick={()=>onRelease(r)}>Liberar reserva</button><button className="complete" onClick={()=>onComplete(r)}>Marcar vendido</button></div></article>})}</div>}

function Calendar({month,selected,deliveries,onMonth,onSelect}:{month:Date;selected:string;deliveries:Delivery[];onMonth:(d:Date)=>void;onSelect:(s:string)=>void}){const year=month.getFullYear(),m=month.getMonth(),days=new Date(year,m+1,0).getDate();let start=new Date(year,m,1).getDay();start=start===0?6:start-1;const cells:Array<Date|null>=[...Array(start).fill(null),...Array.from({length:days},(_,i)=>new Date(year,m,i+1))];while(cells.length%7)cells.push(null);const monthName=new Intl.DateTimeFormat("es-SV",{month:"long",year:"numeric"}).format(month);return <section className="calendar"><header><button onClick={()=>onMonth(new Date(year,m-1,1))} aria-label="Mes anterior">‹</button><h3>{monthName}</h3><button onClick={()=>onMonth(new Date(year,m+1,1))} aria-label="Mes siguiente">›</button></header><div className="weekdays">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map(x=><span key={x}>{x}</span>)}</div><div className="days">{cells.map((d,i)=>d?<button key={i} className={`${isoDate(d)===selected?"selected":""} ${isoDate(d)===isoDate(now)?"today":""}`} onClick={()=>onSelect(isoDate(d))}><b>{d.getDate()}</b>{deliveries.some(x=>x.date===isoDate(d))&&<i>{deliveries.filter(x=>x.date===isoDate(d)).length}</i>}</button>:<span key={i}/>)}</div><button className="today-button" onClick={()=>{onMonth(new Date(now.getFullYear(),now.getMonth(),1));onSelect(isoDate(now))}}>Ir a hoy</button></section>}
function DeliveryCard({delivery:d}:{delivery:Delivery}){return <article className="delivery-card"><div className="date-block"><b>{d.time}</b><span>{money(d.price)}</span></div><div><h3>{d.client}</h3><p>{d.details}</p><small>{d.address}</small><a href={`tel:${d.phone}`}>Llamar al {d.phone}</a></div></article>}
function ProductForm({product,categories,onSubmit}:{product:Product|null;categories:string[];onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){const [cost,setCost]=useState(product?.cost??0),[general,setGeneral]=useState(product?.publicPrice??0),[family,setFamily]=useState(product?.familyPrice??0),[isNew,setIsNew]=useState(false);return <form onSubmit={onSubmit}><span className="eyebrow">{product?"EDITAR PRODUCTO":"NUEVO PRODUCTO"}</span><h2>{product?product.name:"Agregar producto"}</h2><div className="form-grid"><label className="wide">Nombre del producto<input required name="name" defaultValue={product?.name} placeholder="Ejemplo: Vela de vainilla" autoFocus/></label><label className="wide">Cantidad<input required name="quantity" type="number" min="1" step="1" defaultValue={product?.quantity??1}/><small className="field-help">¿Cuántas unidades iguales tienes?</small></label><label className="wide">Categoría<select required={!isNew} name="category" defaultValue={product?.category??categories[0]} disabled={isNew}>{categories.map(c=><option key={c}>{c}</option>)}</select><button type="button" className="new-category-button" onClick={()=>setIsNew(!isNew)}>{isNew?"Elegir una existente":"＋ Crear categoría nueva"}</button></label>{isNew&&<label className="wide new-category">Nombre de la categoría<input required name="newCategory" placeholder="Ejemplo: Accesorios"/></label>}<label className="wide">Precio de compra por unidad<input required name="cost" type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label>Venta general<input required name="publicPrice" type="number" min="0" step="0.01" value={general} onChange={e=>setGeneral(Number(e.target.value))}/><small className="calculated">Ganancia por unidad: {money(general-cost)}</small></label><label>Venta familia<input required name="familyPrice" type="number" min="0" step="0.01" value={family} onChange={e=>setFamily(Number(e.target.value))}/><small className="calculated">Ganancia por unidad: {money(family-cost)}</small></label></div><button className="submit">{product?"Guardar cambios":"Agregar producto"}</button></form>}
function DeliveryForm({date,onSubmit}:{date:string;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit}><span className="eyebrow">NUEVA ENTREGA</span><h2>Agendar una cita</h2><div className="form-grid"><label>Fecha<input required name="date" type="date" defaultValue={date}/></label><label>Hora<input required name="time" type="time" defaultValue="10:00"/></label><label className="wide">Nombre del cliente<input required name="client" placeholder="Nombre completo" autoFocus/></label><label className="wide">Precio de la entrega<input required name="price" type="number" min="0" step="0.01" placeholder="0.00"/></label><label className="wide">Teléfono<input required name="phone" type="tel" placeholder="7000-0000"/></label><label className="wide">¿Qué se entregará?<input required name="details" placeholder="Ejemplo: 2 velas de lavanda"/></label><label className="wide">Lugar de entrega<input required name="address" placeholder="Dirección o punto de referencia"/></label></div><button className="submit">Agregar al calendario</button></form>}
function MovementForm({product:p,available,type,onSubmit}:{product:Product;available:number;type:"sale"|"reserve";onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){const [saleType,setSaleType]=useState<SaleType>("General"),[quantity,setQuantity]=useState(1),price=saleType==="General"?p.publicPrice:p.familyPrice;return <form onSubmit={onSubmit}><span className="eyebrow">{type==="sale"?"NUEVA VENTA":"NUEVA RESERVA"}</span><h2>{p.name}</h2><p className="movement-available">Tienes <b>{available} unidades disponibles</b></p><label className="movement-quantity">Cantidad<input required name="quantity" type="number" min="1" max={available} value={quantity} onChange={e=>setQuantity(Math.min(available,Math.max(1,Number(e.target.value))))}/></label><fieldset><legend>¿Precio para quién?</legend><label className={saleType==="General"?"chosen":""}><input type="radio" name="saleType" value="General" checked={saleType==="General"} onChange={()=>setSaleType("General")}/><span><b>Público general</b><small>{money(p.publicPrice)} por unidad</small></span></label><label className={saleType==="Familia"?"chosen":""}><input type="radio" name="saleType" value="Familia" checked={saleType==="Familia"} onChange={()=>setSaleType("Familia")}/><span><b>Familia</b><small>{money(p.familyPrice)} por unidad</small></span></label></fieldset><div className="sale-summary"><span>Cantidad: <b>{quantity}</b></span><span>Total: <b>{money(price*quantity)}</b></span>{type==="sale"&&<strong>Ganancia: {money((price-p.cost)*quantity)}</strong>}</div><button className="submit">Confirmar {type==="sale"?"venta":"reserva"}</button></form>}
